services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: blog_postgres_dev
    environment:
      POSTGRES_DB: blog_db_dev
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data


volumes:
  postgres_dev_data:

